# Generated by Django 5.2.11 on 2026-03-16 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_livro_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reserva', models.DateField(verbose_name='Data da Reserva')),
                ('data_devolucao', models.DateField(verbose_name='Data da Devolução')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.leitor', verbose_name='Reservista')),
            ],
            options={
                'verbose_name': 'Emprestimo',
                'verbose_name_plural': 'Emprestimos',
            },
        ),
    ]
