# Generated by Django 5.2.11 on 2026-03-16 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_emprestimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='livro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.livro', verbose_name='Livro Reservado'),
            preserve_default=False,
        ),
    ]
